CREATE TABLE uwv_openmatch.js_prov_va AS (

SELECT prov.*, IFNULL(vac.AANT_VA, 0) AS AANT_VA
FROM
(
	SELECT v.BEROEP_CD, v.REFERENTIEBEROEP, v.BEROEPENCLUSTER_CD, v.BEROEPENCLUSTER, v.PROVINCIE, SUM(v.AANT_VA) AS AANT_VA
	FROM va_total v
	GROUP BY v.BEROEP_CD, v.REFERENTIEBEROEP, v.BEROEPENCLUSTER_CD, v.BEROEPENCLUSTER, v.PROVINCIE
) vac
RIGHT JOIN js_prov prov
ON prov.PROVINCIE = vac.PROVINCIE
AND prov.BEROEP_CD = vac.BEROEP_CD
)
;