-- POSTcode
SELECT p.BEROEP_CD, p.REFERENTIEBEROEP, p.BEROEPENCLUSTER_CD, p.BEROEPENCLUSTER, p.POSTCODEGEBIED, p.GEMEENTE, p.PROVINCIE, SUM(v.AANT_VA)
FROM js_pc AS p
LEFT JOIN va_total v
ON p.POSTCODEGEBIED = v.POSTCODEGEBIED
AND p.BEROEP_CD = v.BEROEP_CD
-- AND p.PROVINCIE = v.PROVINCIE
-- AND p.BEROEP_CD = v.BEROEP_CD
GROUP BY p.BEROEP_CD, p.REFERENTIEBEROEP, p.BEROEPENCLUSTER_CD, p.BEROEPENCLUSTER, p.POSTCODEGEBIED, p.GEMEENTE, p.PROVINCIE
;