-- INSERT INTO js_total_v

SELECT prov.*, vac.AANT_VA
FROM
(
	SELECT v.BEROEP_CD, v.REFERENTIEBEROEP, v.BEROEPENCLUSTER_CD, v.BEROEPENCLUSTER, v.PROVINCIE, SUM(v.AANT_VA) AS AANT_VA
	FROM va_total v
	GROUP BY v.BEROEP_CD, v.REFERENTIEBEROEP, v.BEROEPENCLUSTER_CD, v.BEROEPENCLUSTER, v.PROVINCIE
) vac
RIGHT JOIN js_prov prov
ON prov.PROVINCIE = vac.PROVINCIE
AND prov.BEROEP_CD = vac.BEROEP_CD
;