-- Gemeente
CREATE TABLE uwv_openmatch.js_gem_va AS (
SELECT gem.*, IFNULL(vac.AANT_VA, 0) AS AANT_VA
FROM
(
	SELECT v.BEROEP_CD, v.REFERENTIEBEROEP, v.BEROEPENCLUSTER_CD, v.BEROEPENCLUSTER, v.GEMEENTE, v.PROVINCIE, SUM(v.AANT_VA) AS AANT_VA
	FROM va_total v
	GROUP BY v.BEROEP_CD, v.REFERENTIEBEROEP, v.BEROEPENCLUSTER_CD, v.BEROEPENCLUSTER, v.GEMEENTE, v.PROVINCIE
) vac
RIGHT JOIN js_gem gem
ON gem.GEMEENTE = vac.GEMEENTE
AND gem.BEROEP_CD = vac.BEROEP_CD
)
;